const CART = {

  GET_CART_REQUEST: 'GET_CART_REQUEST',
  GET_CART_SUCCESS: 'GET_CART_SUCCESS',
  GET_CART_ERROR: 'GET_CART_ERROR',

  ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  ADD_TO_CART_ERROR: 'ADD_TO_CART_ERROR',

  EDIT_CART_REQUEST: 'EDIT_CART_REQUEST',
  EDIT_CART_SUCCESS: 'EDIT_CART_SUCCESS',
  EDIT_CART_ERROR: 'EDIT_CART_ERROR',

  CHANGE_QUANTITY_REQUEST: 'CHANGE_QUANTITY_REQUEST',
  CHANGE_QUANTITY_SUCCESS: 'CHANGE_QUANTITY_SUCCESS',
  CHANGE_QUANTITY_ERROR: 'CHANGE_QUANTITY_ERROR',

  DELETE_CART_REQUEST: 'EDIT_CART_REQUEST',
  DELETE_CART_SUCCESS: 'DELETE_CART_SUCCESS',
  DELETE_CART_ERROR: 'DELETE_CART_ERROR',

};

export { CART };
